2020-03-13 03:22:27,783 ERROR: Exception on /index [GET] [in d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\pyCharm\Flask-Learing\app\routes.py", line 31, in index
    return render_template('index.html', title='Home', posts=posts, form=form)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\pyCharm\Flask-Learing\app\templates\index.html", line 12, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2020-03-13 03:22:31,786 ERROR: Exception on /index [GET] [in d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\pyCharm\Flask-Learing\app\routes.py", line 31, in index
    return render_template('index.html', title='Home', posts=posts, form=form)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\pycharm\flask-learing\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\pyCharm\Flask-Learing\app\templates\index.html", line 12, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2020-03-13 03:26:50,842 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 03:28:13,611 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 03:32:38,117 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 03:35:43,379 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 03:37:57,434 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 20:21:03,467 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 20:24:13,338 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 20:26:28,026 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
2020-03-13 20:28:45,504 INFO: Microblog startup [in D:\pyCharm\Flask-Learing\app\__init__.py:43]
